version: "3"

services:

  nginx:
    build:
      context: ./bin/nginx
    container_name: 'docker-lemp-nginx'
    ports:
      - '80:80'
    volumes:
      - ./src/backend:/var/www/backend
      - ./.docker/nginx/conf.d:/etc/nginx/conf.d
      - phpmyadmindata:/var/www/phpmyadmin
    depends_on:
      - backend
      - phpmyadmin

  backend:
    build:
      context: ./bin/php8
    container_name: 'docker-lemp-php'
    working_dir: /var/www/backend
    volumes:
      - ./src/backend:/var/www/backend
    depends_on:
      - mysql

  mysql:
    build:
      context:  ./bin/mysql8
    container_name: 'docker-lemp-mysql'
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    volumes:
      - ./.docker/mysql/my.cnf:/etc/mysql/conf.d/my.cnf
      - mysqldata:/var/lib/mysql

  phpmyadmin:
    build:
      context: ./bin/pma
    container_name: 'docker-lemp-myadmin'
    environment:
      PMA_HOST: mysql
    volumes:
      - phpmyadmindata:/var/www/html
    depends_on:
      - mysql

volumes:
  mysqldata:
  phpmyadmindata: